---
- name: Configure Docker on EC2 Instances
  hosts: all
  become: yes

  tasks:
    - name: updating apt
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Stop any container using port 8085
      shell: |
        docker ps -q --filter "publish=8085" | xargs -r docker stop

    - name: Remove any container using port 8085
      shell: |
        docker ps -a -q --filter "publish=8085" | xargs -r docker rm

    - name: Deploy Docker Container
      shell: docker run -itd -p 8085:8081 dnyaneshwarraut/finance-me:1.0
